### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by sqh111** [PRNicovich/ClusDoC#11]
I am a PhD student from Hainan University, China. We recently developed a software for processing SMLM data and wrote an article for submission, and we used the test data( 1.txt) to test our software. First, there is a question I would like to ask you, which two biomolecules were imaged by SMLM to obtain this two-color data? Secondly, we will mention the use of that data in our article. Therefore, in which way would you like us to thank you for your help (acknowledgement or authorship).
Best wishs.

**Comment by PRNicovich** [comment]
Example data in this repo is T cell receptor (TCR; channel 1) and phosphorylated TCR (channel 2).  See Fig 6A and B in the MBoC paper below for similar datasets.

When using public data from this repo, please cite the associated papers:
https://www.pnas.org/doi/10.1073/pnas.1607436113
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5221594/

An acknowledgement in your manuscript would be appreciated if you feel the available data facilitated significant progress in your research.

**Comment by sqh111** [comment]
Thank you for your answer, and who should we thank in the acknowledgements (Sophie V. Pageon and/or Katharina Gaus)?

**Comment by PRNicovich** [comment]
An appropriate acknowledgement would be: 

"We thank the authors of references [Pageon, et al, PNAS] and [Pageon, et al, MBoC] for the dataset used to demonstrate this work. This dataset is available from the authors of the previous works at [insert link]."

**Comment by sqh111** [comment]
Thank you again for your careful reply, I will do so. Best regards.

**Comment by sqh111** [comment]
Hello，Do you still have the data of Fig.6a in ClusDOC paper?

**Comment by sqh111** [comment]
What is the reason why some clusters in PTCR are not co-located with TCR?
![image](https://user-images.githubusercontent.com/53248962/202892792-f39d35b6-b4c4-481f-92bd-83c7132c2fbf.png)

**Comment by PRNicovich** [comment]
I have no information on the content or interpretation of the images.  You are welcome to contact the lead authors on the paper for scientific questions regarding this software.
