### ISSUE TITLE
Clus-DoC with thunderSTORM tables

### ISSUE THREAD

**Issue by Ejdrup** [PRNicovich/ClusDoC#3]
Hi

I'm looking to utilize this tool in my research as keeping our own tools up to date, customizable and error free has become extremely cumbersome. However, I aquire images on a nikon camera and process with ThunderSTORM. My issue lies in not being able to run coloc analysis as my files only contain single-colour and I'd have to feed in two files to have multi-colour images of the same cell.

Is there a way to circumvent this I am missing, or is it possible to implement this? 

Potentially an absolutely wonderful tool though.

**Comment by PRNicovich** [comment]
Given the diversity of SMLM dataset formats, it is impossible to support all from the onset.  This code has been amended several times to add new file format support when requested.  

.\private\Import1File.m controls data import.  Any modifications to support new file formats would be made there.  This was originally written to accept Zeiss-formatted files so all other formats are parsed and output as if they contained the same info in the same format.

That function currently supports some forms of ThunderSTORM output.  ThunderSTORM is highly configurable so it is difficult to support all.  The supported formats have 10, 11, 24, or 26 columns, with contents mapped as defined by the Import1File.m function.  In the past Nikon-generated files have had 24 or 26 columns for 2D or 3D imaging, respectively. It is possible to alter this mapping or accept a different format if an example is provided. 

Currently two color file import requires the output localization lists for each channel to be concatenated into a single file.  This should be straightforward to do with any text editor or to write a small utility to do so. 

If these options don't address your problem then I can edit the import function to support your files.  Would need an example dataset to work against.

**Comment by Ejdrup** [comment]
Thank you for the swift response!

I've managed to get it working by concatenating, creating an 11th column called "Channel" and adding 1's and 2's. I edited the Import1File.m to pull challe from that column rather than filling with "ones".

However, when running the script now the program handles up until the following:

```
DBSCANHandler failed with errors
DoC exited with errors
Invalid MEX-file
'C:\Users\___\Documents\MATLAB\DAT\ClusDoC-Clus-DoC\private\t_dbscan.mexw64': Missing
dependent shared libraries:
'icudt61.dll' required by 'C:\Program
Files\MATLAB\R2019a/bin/win64\icuuc61.dll->C:\Program
Files\MATLAB\R2019a/bin/win64\icuin61.dll->C:\Program
Files\MATLAB\R2019a/bin/win64\libmwi18n.dll->C:\Program
Files\MATLAB\R2019a/bin/win64\libmx.dll->C:\Users\askee\Documents\MATLAB\DAT\ClusDoC-Clus-DoC\private\t_dbscan.mexw64'
'VCOMP100.DLL' required by
'C:\Users\____\Documents\MATLAB\DAT\ClusDoC-Clus-DoC\private\t_dbscan.mexw64'

Error in DBSCANHandler (line 154)
        class = t_dbscan(datathr(:,1), datathr(:, 2), DBSCANParams.minPts,
        DBSCANParams.epsilon, DBSCANParams.threads);

Error in DBSCANonDoCResults (line 75)
                    [~, ClusterCh, ~, classOut, ~, ~, ~, ResultCell{roiIter, cellIter}]
                    = DBSCANHandler(Data_DoC1(:,5:6), ...

Error in ClusDoC>DoC_All (line 2515)
            [ClusterTableCh1, ClusterTableCh2, clusterIDOut, handles.ClusterTable] =
            DBSCANonDoCResults(handles.CellData, handles.ROICoordinates, ...
 
Error while evaluating UIControl Callback.
```

Any error you've encountered before? I have tried redownloading 'icudt61.dll', but that does not fix it.

**Comment by Ejdrup** [comment]
Thank you for the swift reply!

I managed to concatenate the two channels and add a "Channel" column with one's and two's and implemented correspondingly in Import1File.m as you suggested.

However, shortly after finishing the 2nd dbscan the script gives me the following error:

```
DoC exited with errors
Error: File: EvalStatisticsOnDBSCANandDoCResults.m Line: 158 Column: 76
Invalid text character. Check for unsupported symbol, invisible character, or pasting
of non-ASCII characters.

Error in ClusDoC>DoC_All (line 2536)
            EvalStatisticsOnDBSCANandDoCResults(ClusterTableCh1, 1,
            strcat(handles.Outputfolder, '\Clus-DoC Results'));
 
Error while evaluating UIControl Callback.
```

Seen this before?

Hope I'm not too much of an inconvenience.

**Comment by PRNicovich** [comment]
Corrected.  Was issue with wrong comment character in that function.  Had edited earlier due to different issue and error wasn't caught in tests.

Please try latest updates to see if this is resolved.

**Comment by Ejdrup** [comment]
Found the same error. Wonderful.

On several of the test run I get an insanely high amount of CBC values with exactly '0'. Have you run in to this issue?

**Comment by PRNicovich** [comment]
Could you please provide more info on where you are seeing that value? 

My first guess is that colocalization values of '0' correspond to points that are neither colocalized or anti-colocalized with other points.  If no points are within the search radius either in the same channel or in others this could arise.  It also could arise if these points are excluded from clusters by the DBSCAN step.  Within the DBSCAN step itself, '0' cluster designation should correspond to background (non-clustered) points.

**Comment by Ejdrup** [comment]
> If no points are within the search radius either in the same channel or in others this could arise.

This seems to be the case. We're still discussing the biological implications, but which part of the program handles those situations if I want to either remove these or assign them -1, depending on context?
